name: Revision post

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: instalar dependencias con maven
      run: mvn install

    - name: ejecutar pruebas 3
      run: mvn clean verify

    - name: ejecutar pruebas
      run: mvn clean test

    - name: ejecutar pruebas 1
      run: mvn -Dtest=*Runner test

    - name: ejecutar pruebas 2
      run: mvn -Dtest=menuRunner test
